Repository thangchung/awesome-dotnet-core, pull requests merged in 2018-02, with the labels that each got.

#212 Add Fake JSON Server
  README.md
Labels: review

#214 Add CurlThin
  README.md
Labels: review

#203 add MySqlConnector
  README.md
Labels: review

#209 Add ConsoleTableExt - easy/fluent way to create table for console app
  README.md
Labels: review

#216 Add Minicover - Minimalist Code Coverage Tool for .NET Core.
  README.md
Labels: review

#204 add websocket-manager
  README.md
Labels: review

#208 add bot section & NadekoBot
  README.md
Labels: review

#201 add CommandLineUtils package
  README.md
Labels: review

#126 Added GLFWDotNet and SharpBgfx.
  README.md
Labels: enhancement

#134 Adding SqlKata under Orm
  README.md
Labels: enhancement, review

#144 Adding Exploring .NET Core with Microservices, ASP.NET Core, and Entity Framework Core to the book list
  README.md
Labels: review
