Repository thangchung/awesome-dotnet-core, pull requests merged in 2018-07, with the labels that each got.

#283 Added MQTTnet to 'Queue and Messaging' section
  README.md
Labels: In Preview

#246 NBlockchain
  README.md
Labels: Invalid Alphabet Order, review

#250 Adding netDumbster to the Mail list.
  README.md
Labels: done, invalid, review

#245 Added FastExpressionCompiler to Misc
  README.md
Labels: review

#262 GenVue sample project added to Sample Project List
  README.md
Labels: invalid

#307 Added nsec to Cryptography section
  README.md
Labels: Reviewed

#252 Added Grace to IOC
  README.md
Labels: In Preview

#305 Added PuppeteerSharp to Misc section
  README.md
Labels: In Preview

#303 Added dotnet cli cheat sheet
  README.md
Labels: Reviewed

#253 Add AdvanceDL
  README.md
Labels: Reviewed

#265 Add Mond scripting language
  README.md
Labels: Reviewed

#319 Add nopCommerce.
  README.md
Labels: In Preview

#317 Added Otp.NET to Misc section
  README.md
Labels: Reviewed

#322 Add PayPal SDK
  README.md
Labels: Reviewed

#323 Added Fody to Misc section
  README.md
Labels: In Preview

#186 Add Xer.Cqrs
  README.md
Labels: review

#309 Added MagicScaler to Graphics section
  README.md
Labels: Reviewed

#320 Add LibVLCSharp
  README.md
Labels: In Discussion, In Preview

#218 Added Swastika I/O Core CMS.
  README.md
Labels: Reviewed

#240 Add CAP to [Application Frameworks]
  README.md
Labels: In Preview

#230 add typed routing
  README.md
Labels: review

#176 Add OpenCQRS to Queue and Messaging
  README.md
Labels: Reviewed

#328 add PostgreSQL entity framework
  README.md
Labels: In Preview

#344 Added Chloe to ORM section
  README.md
Labels: Reviewed

#345 Added AutoDiff library
  README.md
Labels: Reviewed

#128 Add CakeMail.RestClient
  README.md
Labels: enhancement
