Repository thangchung/awesome-dotnet-core, pull requests merged in 2018-11, with the labels that each got.

#415 add FastReport Open Source
  README.md
Labels: In Preview

#210 add openid debugger
  README.md
Labels: review

#374 Add Networker
  README.md
Labels: Reviewed

#228 add trackable entities core
  README.md
Labels: review

#219 add data access
  README.md
Labels: review

#333 add Prometheus.Client
  README.md
Labels: In Discussion, question

#324 Added the Qml.Net project.
  README.md
Labels: In Preview, Invalid Alphabet Order

#369 Add Butterfly Server .NET
  README.md
Labels: In Discussion
