Repository thangchung/awesome-dotnet-core, pull requests merged in 2018-08, with the labels that each got.

#348 Clean Architecture Service Template Added
  README.md
Labels: In Preview

#268 Add Database Resource Localization for .NET Core
  README.md
Labels: Reviewed

#226 add auto history
  README.md
Labels: review

#329 add dapper graphql
  README.md
Labels: In Preview

#355 Flubu
  README.md
Labels: In Preview

#357 Add NBXplorer
  README.md
Labels: Invalid Alphabet Order

#327 add extension
  README.md
Labels: In Preview

#241 Add Eighty to Misc
  README.md
Labels: Project is possibly too small, Reviewed
