Repository thangchung/awesome-dotnet-core, pull requests merged in 2018-06, with the labels that each got.

#274 Added Carter - A Nancy-esque routing library for ASP.Net Core
  README.md
Labels: review

#271 add dotnet serve
  README.md
Labels: review

#205 add aspnet-core-react-template
  README.md
Labels: review

#202 add electron .net
  README.md
Labels: review

#206 add opencvcsharp
  README.md
Labels: review

#270 add graphql dotnet server
  README.md
Labels: review

#213 add dotnet script
  README.md
Labels: review

#278 add aspnet core spa
  README.md
Labels: review

#169 Add posh-dotnet
  README.md
Labels: question, review

#231 add sharp repo
  README.md
Labels: review

#258 Add another blog engine
  README.md
Labels: review

#243 Added RazorLight to Template Engines
  README.md
Labels: review

#242 Add FlubuCore
  README.md
Labels: review

#233 Added Piranha CMS
  README.md
Labels: review

#264 Added entry for the new Channel9 youtube channel.
  README.md
Labels: review

#251 Add cosullivan/SmtpServer
  README.md
Labels: review

#296 Added UnitsNet to Misc section
  README.md
Labels: done
