Repository thangchung/awesome-dotnet-core, pull requests merged in 2018-09, with the labels that each got.

#362 Add Gofer.NET
  README.md
Labels: Invalid Alphabet Order

#375 Add Inyector
  README.md
Labels: Reviewed

#364 Create BuiltWithDotNet.md
  README.md
Labels: In Discussion
